name: lando-demo
recipe: drupal10
excludes:
  - .
config:
  webroot: web
  php: '8.3'
  composer_version: '2'
  drush: false
  xdebug: debug
  database: mariadb
env_file:
  - .lando/lando.env
services:
  # appserver
  appserver:
    ssl: false
    portforward: false
    scanner: false
    overrides:
      environment:
        PHP_MEMORY_LIMIT: 128M
    build_as_root:
      - rm -f /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - apt-get install -y ca-certificates curl gnupg; mkdir -p /etc/apt/keyrings; curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg; NODE_MAJOR=20; echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list
      - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
      - echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
      - apt-get update && apt-get install --no-install-recommends -y yarn mc net-tools iputils-ping python nodejs
      # - cd /tmp && git clone https://github.com/longxinH/xhprof.git
      # - cd /tmp/xhprof/extension && phpize && ./configure && make && make install
      # - echo 'extension=xhprof.so' > /usr/local/etc/php/conf.d/xhprof.ini
    build:
      - ln -sf /app/.lando/git-completion.bash  /var/www/.git-completion.bash
      - ln -sf /app/.lando/git-prompt.sh /var/www/.git-prompt.sh
      - ln -sf /app/.lando/bashrc /var/www/.bashrc
  # varnish
  varnish:
    type: varnish:6
    ssl: false
    portforward: false
    scanner: false
    app_mount: false
    backends:
      - appserver
    backend_port: 80
    overrides:
      environment:
        VARNISH_ALLOW_UNRESTRICTED_PURGE: 1
    config:
      vcl: .lando/varnish/default.vcl
  # database
  database:
    type: compose
    ssl: false
    portforward: false
    scanner: false
    app_mount: false
    services:
      image: mariadb:10.6
      command: docker-entrypoint.sh mysqld
      entrypoint: docker-entrypoint.sh
      environment:
        - MARIADB_ROOT_PASSWORD=root
        - MARIADB_DATABASE=drupal
        - MARIADB_USER=drupal
        - MARIADB_PASSWORD=drupal
      volumes:
        - database_volume:/var/lib/mysql
    volumes:
      database_volume:
    run_as_root:
      # Create extra databases.
      - mysql -uroot -proot -e "SET GLOBAL TRANSACTION ISOLATION LEVEL READ COMMITTED;"
  # phpmyadmin
  phpmyadmin:
    type: phpmyadmin
    ssl: false
    portforward: false
    scanner: false
    app_mount: false
    overrides:
      environment:
        - PMA_PASSWORD=root
  # memcached
  memcached:
    type: memcached:custom
    ssl: false
    portforward: false
    scanner: false
    app_mount: false
    overrides:
      image: memcached
      command: ["-m", "512"]
      entrypoint: memcached
  # solr
  solr:
    type: solr
    ssl: false
    portforward: false
    scanner: false
    app_mount: false
    core: collection1
    config:
      dir: .lando/solr/config
  # elasticsearch
  elasticsearch:
    type: compose
    ssl: false
    portforward: false
    scanner: false
    app_mount: false
    services:
      image: elasticsearch:7.17.5
      command: ["/bin/tini", "--", "/usr/local/bin/docker-entrypoint.sh", "eswrapper"]
      environment:
        - node.name=drupal-es01
        - cluster.name=drupal-es01-docker-cluster
        - cluster.initial_master_nodes=drupal-es01
        - bootstrap.memory_lock=true
        - "ES_JAVA_OPTS=-Xms128m -Xmx128m"
        - http.cors.enabled=true
        - http.cors.allow-origin=/.*/
      ulimits:
        memlock:
          soft: -1
          hard: -1
      volumes:
        - es_volume:/usr/share/elasticsearch/data
    volumes:
      es_volume:
tooling:
  blt:
    service: appserver
    cmd: /app/vendor/bin/blt
  node:
    service: appserver
  npm:
    service: appserver
  xdebug-on:
    service: appserver
    description: Enable xdebug for apache.
    cmd: "docker-php-ext-enable xdebug && /etc/init.d/apache2 reload"
    user: root
  xdebug-off:
    service: appserver
    description: Disable xdebug for apache.
    cmd: "rm /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && /etc/init.d/apache2 reload"
    user: root
proxy:
  appserver:
    - lando-demo.lndo.site
  varnish:
    - varnish.lando-demo.lndo.site
  phpmyadmin:
    - pma.lando-demo.lndo.site
  solr:
    - solr.lando-demo.lndo.site:8983
  elasticsearch:
    - elasticsearch.lando-demo.lndo.site:9200
