sync:
  defaults:
    # flushOnCreate: true
    ignore:
      vcs: false
      paths:
        - .DS_Store
        - .history/
        - .idea/
        - .code/
        - .vscode/
        - react-js-sample/node_modules/
    permissions:
      defaultFileMode: 644
      defaultDirectoryMode: 755
